FROM openjdk:17
COPY ./target/distributed.search-1.0-SNAPSHOT-jar-with-dependencies.jar distributed.search-1.0-SNAPSHOT-jar-with-dependencies.jar
#CMD ["java","-jar","distributed.search-1.0-SNAPSHOT.jar"]
