FROM openjdk:17
COPY ./target/front.end-1.0-SNAPSHOT-jar-with-dependencies.jar front.end-1.0-SNAPSHOT-jar-with-dependencies.jar

#CMD ["java","-jar","front.end-1.0-SNAPSHOT-jar-with-dependencies.jar", "9092]
