- hosts: localhost
  tasks:
  - name: stop current running container
    command: "{{ item }}"
    with_items:
    - docker stop frontend1
    - docker stop frontend2
    - docker stop haproxy1
    - docker stop haproxy2
    - docker stop zoo1
    ignore_errors: yes #container is not available
    
  - name: remove stopped container
    command: "{{ item }}"
    with_items:
    - docker rm frontend1
    - docker rm frontend2
    - docker rm haproxy1
    - docker rm haproxy2
    - docker rm zoo1
    ignore_errors: yes #container is not available
    
  - name: remove image
    command: "{{ item }}"
    with_items:
    - docker rmi search-frontend
    ignore_errors: yes
    
  - name: build docker image  using jar file
    command: "{{ item }}"
    with_items:
    - docker build -t search-frontend ./distributed-search-frontend
    args:

  - name: run compose
    docker_compose:
        project_src: /home/dockeradmin/compose-and-configs/
        files:
        - docker-compose.yml
        state: present
