version: "3"
services:
        zoo1:
            image: zookeeper:3.7.0
            container_name: zoo1
            restart: always
            networks: 
                - search-network
            volumes: 
                - ./zoo.cfg:/conf/zoo.cfg  
                
        haproxy2:
            image: haproxy
            container_name: haproxy2
            restart: always
            networks: 
                - search-network
            volumes: 
                - ./haproxyLB2.cfg:/usr/local/etc/haproxy/haproxy.cfg   
            depends_on: 
                - zoo1
                
        coordinator1:
            image: search-node
            container_name: coordinator1
            restart: always
            command: java -jar distributed.search-1.0-SNAPSHOT-jar-with-dependencies.jar 9095
            networks: 
                - search-network
                
        coordinator2:
            image: search-node
            container_name: coordinator2
            restart: always
            command: java -jar distributed.search-1.0-SNAPSHOT-jar-with-dependencies.jar 9096
            networks: 
                - search-network
            depends_on: 
                - haproxy2
                
        worker1:
            image: search-node
            container_name: worker1
            restart: always
            command: java -jar distributed.search-1.0-SNAPSHOT-jar-with-dependencies.jar 9097
            networks: 
                - search-network
            depends_on: 
                - coordinator1
                - coordinator2
        
        haproxy1:
            image: haproxy
            container_name: haproxy1
            restart: always
            networks: 
                - search-network
            ports:
                - 9091:9091
            volumes: 
                - ./haproxyLB1.cfg:/usr/local/etc/haproxy/haproxy.cfg
            depends_on: 
                - coordinator1
        
        frontend1:
            image: search-frontend
            container_name: frontend1
            restart: always
            networks: 
                - search-network
            command: java -jar front.end-1.0-SNAPSHOT-jar-with-dependencies.jar 9092
            depends_on: 
                - haproxy1  

networks:
    search-network:
        driver: bridge
    


